### ISSUE TITLE
4.6_랜덤포레스트_손글씨분류.ipynb 에러

### ISSUE THREAD

**Issue by acumox** [wikibook/machine-learning#5]
안녕하세요
cv_list = [    
            ['random_forest',rf_cv_scores],
            ['decision_tree',dt_cv_scores],
          ]
df = pd.DataFrame.from_items(cv_list)
이렇게 입력후 아래와 같은 에러가 나왔어요

AttributeError                            Traceback (most recent call last)

<ipython-input-6-a8337b4c200c> in <module>()
      3             ['decision_tree',dt_cv_scores],
      4           ]
----> 5 df = pd.DataFrame.from_items(cv_list)

AttributeError: type object 'DataFrame' has no attribute 'from_items'

해결방법 부탁드립니다.
감사합니다

**Comment by minsuk-heo** [comment]
팬더스 버전이 업데이트 되서 기존 pd.DataFrame.from_items가 지원되지 않아 발생되는 문제입니다.
아래와 같이 변경하셔서 실행하시면 됩니다. 감사합니다.

cv_list = {'random_forest': rf_cv_scores, 'decision_tree': dt_cv_scores}
df = pd.DataFrame.from_dict(cv_list)
