### ISSUE TITLE
4.2_농구선수_데이터분석.ipynb 에서 

### ISSUE THREAD

**Issue by hamonika00** [wikibook/machine-learning#6]
구글코랩에서 스틸, 2점슛 데이터 시각화 부분에서 다음과 같은 error가 발생됩니다.

TypeError                                 Traceback (most recent call last)

[<ipython-input-5-a5591ae68ffd>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # 스틸, 2점슛 데이터 시각화
----> 6 sns.lmplot('STL', '2P', data=df, fit_reg=False,  # x 축, y 축, 데이터, 라인 없음
      7            scatter_kws={"s": 150}, # 좌표 상의 점의 크기
      8            markers=["o", "x"],

TypeError: lmplot() got multiple values for argument 'data'

**Comment by wikibook** [comment]
@hamonika00 님, 안녕하세요.
위키북스 담당자입니다. 

말씀해 주신 내용을 저자분께 전달했고, 다음과 같은 답신을 전달해 드립니다.

----
안녕하세요, 문제 발견해주시고 알려주셔서 감사합니다. 
  sns.lmplot 라이브러리가 업데이트되어 나타난 에러이구요, x축과 y축을 아래와 같이 직접 명시해주면 해결됩니다.

~~~
sns.lmplot(x='STL', y='2P', data=df, fit_reg=False,  # x 축, y 축, 데이터, 라인 없음
           scatter_kws={"s": 150}, # 좌표 상의 점의 크기
           markers=["o", "x"],
           hue="Pos") # 예측값
~~~
----

아울러 해당 노트북도 업데이트해서 저장소에 업로드했는데, 번거로우시더라도 새로 내려받으셔서 실습 진행 부탁드립니다.

그럼 참고 부탁드리고요, 오늘도 좋은 하루 보내세요.
고맙습니다.
