### ISSUE TITLE
베르누이 나이브 베이즈를 활용한 스팸 분류 파트에 나오는 이슈

### ISSUE THREAD

**Issue by Jongwoo0101** [wikibook/machine-learning#7]
## 개정판 4장 111쪽에 나오는 코드 중
[전체코드](https://github.com/wikibook/machine-learning/blob/master/jupyter_notebook/4.5_%EB%B2%A0%EB%A5%B4%EB%88%84%EC%9D%B4_%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A6%88_%EC%8A%A4%ED%8C%B8%ED%95%84%ED%84%B0_%EC%8B%A4%EC%8A%B5.ipynb)
```py
cv.inverse_transform(encoded_input[0])
```
이 부분을 그대로 입력할 경우 
```
ValueError: Expected 2D array, got 1D array instead:
```
라는 에러가 나오는데 inverse_transform 함수에 전달된 입력이 1차원 배열인데, 이 함수는 2차원 배열을 예상하기 때문에 발생하므로
```py
cv.inverse_transform(encoded_input[0].reshape(1, -1))
````
다음과 같이 reshape을 해야 [array(['free', 'game', 'only', 'today'], dtype='<U9')] 가 나옵니다.

**Comment by Jongwoo0101** [comment]
바로 다음 코드셀에서도 
```py
get_feature_names()
```
는 메서드 이름이
```py
get_feature_names_out()
```
로 바뀌었기 때문에 수정 부탁드립니다~!

**Comment by Jongwoo0101** [comment]
다항분포 나이브 베이즈를 활용한 영화 리뷰 분류 파트인 116, 117쪽에서도 동일한 문제가 나옵니다! 확인하시고 수정 부탁드릴게요~

**Comment by minsuk-heo** [comment]
안녕하세요, 알려주셔서 감사합니다.
개정판 실습 코드는 2.0 브랜치에서 관리되고 있구요, 발견해주신 문제 중
cv.inverse_transform(encoded_input[0].reshape(1, -1))
는 실습 코드에 이미 반영되어 있네요.
get_feature_names_out() 문제 알려주셔서 감사합니다. 제가 바로 실습코드에 반영하고,
다음 개정판 책에 수정 사항 반영토록 진행하겠습니다. 감사합니다.

전체코드: https://github.com/wikibook/machine-learning/blob/2.0/jupyter_notebook/4.5_%EB%B2%A0%EB%A5%B4%EB%88%84%EC%9D%B4_%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A6%88_%EC%8A%A4%ED%8C%B8%ED%95%84%ED%84%B0_%EC%8B%A4%EC%8A%B5.ipynb

**Comment by minsuk-heo** [comment]
아래와 같이 진행했습니다. 이슈 리포트해주셔서 정말 감사합니다.
https://github.com/wikibook/machine-learning/commit/7f885e685525b903543081f33c67bb6fdc294e56
https://github.com/wikibook/machine-learning/commit/60791dd58270dd029d3c89021c01af85e7e6416b

**Comment by wikibook** [comment]
@Jongwoo0101 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/mymlrev/)에 해당 내용을 등록했습니다.

불편을 드려 죄송하고, 오류를 바로잡을 수 있게 해주셔서 감사합니다. 보내주신 내용은 다음 인쇄 때 반영하도록 하겠습니다.
그럼 오늘도 좋은 하루 보내세요..!
고맙습니다.

**Comment by Jongwoo0101** [comment]
빠른 답변 & 수정 감사합니다~ 좋은 하루 보내세요! 😄
